#  docker-compose -f docker-compose.yml config check validate config
version: "3.2"
services:
  portainer:
    image: "portainer/portainer:latest"
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - portainer_data:/data
    labels:
      com.docker.compose.project: "portainer"
    networks:
      - reverse_proxy
      - agent_network_dtics

volumes:
  portainer_data:

networks:
  reverse_proxy:
    external:
      name: reverse_proxy
  agent_network_dtics:
    driver: overlay
