#  docker-compose -f docker-compose.yml config check validate config
version: "3.7"
services:
  portainer:
    image: "portainer/portainer:latest"
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - portainer_data:/data
    labels:
      com.docker.compose.project: "portainer"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.interconnect == si
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    environment:
      VIRTUAL_HOST: "portainer.local.com"
      VIRTUAL_PORT: "8101:8101"
      DHPARAM_GENERATION: "true"
    networks:
      - rproxy
      - agent_network_dtics

volumes:
  portainer_data:

networks:
  rproxy:
    external:
      name: reverse_proxy
  agent_network_dtics:
    driver: overlay
