#  docker-compose -f docker-compose.yml config check validate config
version: "3.7"
services:
  portainer:
    image: "portainer/portainer:latest"
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    labels:
      com.docker.compose.project: "portainer"
    networks:
      - reverse_proxy
      - swarm_network
volumes:
  portainer_data:

networks:
  default:
    driver: bridge
    external:
      name: frontend-network
  reverse_proxy:
    external:
      name: reverse_proxy
  network-backend:
    external:
      name: backend-network
  swarm_network:
    driver: overlay
