#  docker-compose -f docker-compose.yml config check validate config
version: "3.7"
services:
  portainer:
    image: "portainer/portainer:latest"
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    labels:
      com.docker.compose.project: "portainer"
    networks:
      - reverse_proxy
      - swarm_network

  swarmpit:
    image: swarmpit/swarmpit:1.8
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - swarm_network
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
      placement:
        constraints:
          - node.role == manager

volumes:
  portainer_data:
    name: portainer_data
    driver: local

networks:
  default:
    driver: bridge
    external:
      name: frontend-network
  reverse_proxy:
    external:
      name: reverse_proxy
  network-backend:
    external:
      name: backend-network
  swarm_network:
    driver: overlay
    external:
      name: swarm_network
